// This file is automatically generated by build.rs
// Do not edit this file manually!

use std::collections::HashMap;

use horizon_plugin_api::{LoadedPlugin, Plugin, Pluginstate};
pub use player_lib;
pub use player_lib::Plugin as player_lib_plugin;
pub use player_lib::*;

// Invoke the macro with all discovered plugins
pub fn load_plugins() -> HashMap<String, (Pluginstate, Plugin)> {
    let plugins = crate::load_plugins!(player_lib);
    plugins
}
